POST http://localhost:3001/api/user
content-type: application/json

{
    "fullname":"Alex Romanov",
    "username":"alex123",
    "password":"password123",
    "email":"alexr@gmail.com",
    "phone":"977-1234567890",
    "address":[{"district":"Chitwan","city":"Bharatpur-11","landmark":"near gaida"}],
    "userType":"user",
    "isDisabled":false
}

###
GET http://localhost:3001/api/user

###
POST http://localhost:3001/api/products
content-type: application/json

  {
    "productName": "Frooti Mango Drink",
    "categoryId": "SOFT-DRINK",
    "productBrand": "Parle-Agro",
    "skus": [
      {
        "img": "",
        "sku": "Frooti_Mango_Drink_250ML",
        "price": 50,
        "quantity": 567,
        "feature": "Made with real mango pulp from the freshest of mangoes, Frooti satisfies the craving for this popular seasonal fruit throughout the year.",
        "alcohol": "0"
      },
      {
        "img": "",
        "sku": "Frooti_Mango_Drink_500ML",
        "price": 90,
        "quantity": 567,
        "feature": "Made with real mango pulp from the freshest of mangoes, Frooti satisfies the craving for this popular seasonal fruit throughout the year.",
        "alcohol": "0"
      },
      {
        "img": "",
        "sku": "Frooti_Mango_Drink_200ML",
        "price": 30,
        "quantity": 567,
        "feature": "Made with real mango pulp from the freshest of mangoes, Frooti satisfies the craving for this popular seasonal fruit throughout the year.",
        "alcohol": "0"
      }
    ],
    "manufacture": "Parley Agro Pvt. Ltd."
  }
###
GET http://localhost:3001/api/products

###
GET http://localhost:3001/api/products/items


###
GET http://localhost:3001/api/order
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NWRkNTk4NWEyNTRkOWQxNDA2NjdhNyIsInVzZXJuYW1lIjoiYWxleDEyMyIsInVzZXJUeXBlIjoidXNlciIsImlzRGlzYWJsZWQiOmZhbHNlLCJpYXQiOjE3MDA5MzUzODYsImV4cCI6MTcwMDkzODA4Nn0.ql8YHAA2WEuMEQBxSXwci5H-LmxnVEKnJshGu_1VUvM
###
POST http://localhost:3001/api/order
content-type: application/json

{
    "userId":"654f93c7fc6756ed7c122d68",
    "paymentStatus":"pending",
    "status":"placed",
    "amount":1597,
    "items":[{"sku":"Tuborg 500ml Beer CAN",""quantity"":1,"price":1597}],
    "shippingAddress":{"district":"Lalitpur","city":"Bakha 10","landmark":"labim mall south"}
}


###
POST http://localhost:3001/api/login
content-type: application/json

{
    "username":"alex123",
    "password":"password123",
    "isEmail":false
}


